### ISSUE TITLE
App redirects to offline page even though online

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/fake-news-detector-fd#18]

**Comment by blenderskool** [comment]
Offline checking is disabled as of now, as it must be dealt through service workers. :confused:

**Comment by neelkamath** [comment]
Will this be a problem when it's online?

**Comment by blenderskool** [comment]
@neelkamath It won't be a problem in online, just that in offline there won't be offline error check and would show the placeholder content.
Also, the PWA parts remain unaffected.

**Comment by neelkamath** [comment]
Please close this issue.
